diff --git a/Makefile b/Makefile
index e504646..07c1f2c 100644
--- a/Makefile
+++ b/Makefile
@@ -19,6 +19,21 @@ versions:
 		fi \
 	done
 
+create-patch:
+	@mkdir -p patches
+	@echo -e "\e[1;34m[+] Creating and splitting patch from latest commit...\e[0m"
+	@git format-patch -1 HEAD --stdout | awk '\
+		/^diff --git a\// { \
+			if (out) close(out); \
+			fname = $$3; \
+			sub(/^a\//, "", fname); \
+			gsub(/\//, "_", fname); \
+			out = "patches/" fname ".patch"; \
+		} \
+		{ if (out) print >> out } \
+	'
+	@echo -e "\e[1;32m[+] Individual patch files saved in patches/\e[0m"
+
 PATCH:=./name.patch
 patch:
 	@if [ -f ${PATCH} ]; then \
@@ -32,6 +47,16 @@ patch:
 		echo -e "\e[1;31m[+] ${PATCH} file does not exist"; \
 	fi
 
+patch-all:
+	@for patchfile in patches/*.patch; do \
+		for f in $(wildcard */); do \
+			if [[ -d "$$f" && -f "$$f/Makefile" ]]; then \
+				echo -e "\e[1;35m[+] Patching $$f with $$patchfile\e[0m"; \
+				patch -d $$f --backup-if-mismatch -p2 < "$$patchfile"; \
+			fi \
+		done \
+	done
+
 test:
 	@for DIR_NAME in $(wildcard */); do \
 		if [ -f $$DIR_NAME/Makefile ]; then \
diff --git a/Makefile b/Makefile
index e504646..07c1f2c 100644
--- a/Makefile
+++ b/Makefile
@@ -19,6 +19,21 @@ versions:
 		fi \
 	done
 
+create-patch:
+	@mkdir -p patches
+	@echo -e "\e[1;34m[+] Creating and splitting patch from latest commit...\e[0m"
+	@git format-patch -1 HEAD --stdout | awk '\
+		/^diff --git a\// { \
+			if (out) close(out); \
+			fname = $$3; \
+			sub(/^a\//, "", fname); \
+			gsub(/\//, "_", fname); \
+			out = "patches/" fname ".patch"; \
+		} \
+		{ if (out) print >> out } \
+	'
+	@echo -e "\e[1;32m[+] Individual patch files saved in patches/\e[0m"
+
 PATCH:=./name.patch
 patch:
 	@if [ -f ${PATCH} ]; then \
@@ -32,6 +47,16 @@ patch:
 		echo -e "\e[1;31m[+] ${PATCH} file does not exist"; \
 	fi
 
+patch-all:
+	@for patchfile in patches/*.patch; do \
+		for f in $(wildcard */); do \
+			if [[ -d "$$f" && -f "$$f/Makefile" ]]; then \
+				echo -e "\e[1;35m[+] Patching $$f with $$patchfile\e[0m"; \
+				patch -d $$f --backup-if-mismatch -p2 < "$$patchfile"; \
+			fi \
+		done \
+	done
+
 test:
 	@for DIR_NAME in $(wildcard */); do \
 		if [ -f $$DIR_NAME/Makefile ]; then \
diff --git a/Makefile b/Makefile
index e504646..07c1f2c 100644
--- a/Makefile
+++ b/Makefile
@@ -19,6 +19,21 @@ versions:
 		fi \
 	done
 
+create-patch:
+	@mkdir -p patches
+	@echo -e "\e[1;34m[+] Creating and splitting patch from latest commit...\e[0m"
+	@git format-patch -1 HEAD --stdout | awk '\
+		/^diff --git a\// { \
+			if (out) close(out); \
+			fname = $$3; \
+			sub(/^a\//, "", fname); \
+			gsub(/\//, "_", fname); \
+			out = "patches/" fname ".patch"; \
+		} \
+		{ if (out) print >> out } \
+	'
+	@echo -e "\e[1;32m[+] Individual patch files saved in patches/\e[0m"
+
 PATCH:=./name.patch
 patch:
 	@if [ -f ${PATCH} ]; then \
@@ -32,6 +47,16 @@ patch:
 		echo -e "\e[1;31m[+] ${PATCH} file does not exist"; \
 	fi
 
+patch-all:
+	@for patchfile in patches/*.patch; do \
+		for f in $(wildcard */); do \
+			if [[ -d "$$f" && -f "$$f/Makefile" ]]; then \
+				echo -e "\e[1;35m[+] Patching $$f with $$patchfile\e[0m"; \
+				patch -d $$f --backup-if-mismatch -p2 < "$$patchfile"; \
+			fi \
+		done \
+	done
+
 test:
 	@for DIR_NAME in $(wildcard */); do \
 		if [ -f $$DIR_NAME/Makefile ]; then \
diff --git a/Makefile b/Makefile
index 07c1f2c..49323ab 100644
--- a/Makefile
+++ b/Makefile
@@ -21,8 +21,8 @@ versions:
 
 create-patch:
 	@mkdir -p patches
-	@echo -e "\e[1;34m[+] Creating and splitting patch from latest commit...\e[0m"
-	@git format-patch -1 HEAD --stdout | awk '\
+	@echo -e "\e[1;34m[+] Creating and splitting patch from latest commit (excluding patches/)...\e[0m"
+	@git diff HEAD^ HEAD -- . ':(exclude)patches/' | awk '\
 		/^diff --git a\// { \
 			if (out) close(out); \
 			fname = $$3; \
diff --git a/Makefile b/Makefile
index e504646..c4ed576 100644
--- a/Makefile
+++ b/Makefile
@@ -19,6 +19,22 @@ versions:
 		fi \
 	done
 
+create-patch:
+	@mkdir -p patches
+	@echo -e "\e[1;34m[+] Creating and splitting patch from branch 'cla' against 'main' (excluding patches/)...\e[0m"
+	@git fetch origin main >/dev/null 2>&1
+	@git diff origin/main...HEAD -- . ':(exclude)patches/' | awk '\
+		/^diff --git a\// { \
+			if (out) close(out); \
+			fname = $$3; \
+			sub(/^a\//, "", fname); \
+			gsub(/\//, "_", fname); \
+			out = "patches/" fname ".patch"; \
+		} \
+		{ if (out) print >> out } \
+	'
+	@echo -e "\e[1;32m[+] Patch files saved to ./patches/\e[0m"
+
 PATCH:=./name.patch
 patch:
 	@if [ -f ${PATCH} ]; then \
@@ -32,6 +48,16 @@ patch:
 		echo -e "\e[1;31m[+] ${PATCH} file does not exist"; \
 	fi
 
+patch-all:
+	@for patchfile in patches/*.patch; do \
+		for f in $(wildcard */); do \
+			if [[ -d "$$f" && -f "$$f/Makefile" ]]; then \
+				echo -e "\e[1;35m[+] Patching $$f with $$patchfile\e[0m"; \
+				patch -d $$f --backup-if-mismatch -p2 < "$$patchfile"; \
+			fi \
+		done \
+	done
+
 test:
 	@for DIR_NAME in $(wildcard */); do \
 		if [ -f $$DIR_NAME/Makefile ]; then \
diff --git a/Makefile b/Makefile
index e504646..c4ed576 100644
--- a/Makefile
+++ b/Makefile
@@ -19,6 +19,22 @@ versions:
 		fi \
 	done
 
+create-patch:
+	@mkdir -p patches
+	@echo -e "\e[1;34m[+] Creating and splitting patch from branch 'cla' against 'main' (excluding patches/)...\e[0m"
+	@git fetch origin main >/dev/null 2>&1
+	@git diff origin/main...HEAD -- . ':(exclude)patches/' | awk '\
+		/^diff --git a\// { \
+			if (out) close(out); \
+			fname = $$3; \
+			sub(/^a\//, "", fname); \
+			gsub(/\//, "_", fname); \
+			out = "patches/" fname ".patch"; \
+		} \
+		{ if (out) print >> out } \
+	'
+	@echo -e "\e[1;32m[+] Patch files saved to ./patches/\e[0m"
+
 PATCH:=./name.patch
 patch:
 	@if [ -f ${PATCH} ]; then \
@@ -32,6 +48,16 @@ patch:
 		echo -e "\e[1;31m[+] ${PATCH} file does not exist"; \
 	fi
 
+patch-all:
+	@for patchfile in patches/*.patch; do \
+		for f in $(wildcard */); do \
+			if [[ -d "$$f" && -f "$$f/Makefile" ]]; then \
+				echo -e "\e[1;35m[+] Patching $$f with $$patchfile\e[0m"; \
+				patch -d $$f --backup-if-mismatch -p2 < "$$patchfile"; \
+			fi \
+		done \
+	done
+
 test:
 	@for DIR_NAME in $(wildcard */); do \
 		if [ -f $$DIR_NAME/Makefile ]; then \
