name: Create Patches

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  generate-patches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build dependencies
        run: sudo apt-get update && sudo apt-get install -y make

      - name: Run make create-patch
        run: make create-patch

      - name: Upload patch files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: split-patches
          path: patches/
